import images from "../assets/images/images";

export const eventsInfo = [
	{
		id: 2,
		date: "1 декабря",
		time: "12:00",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "1000 ₸",
		img: images.eventImg1,
		name: "Тюркский разговорник",
		link: "https://sxodim.com/almaty/event/komediynoe-shou-tyurkskiy-razgovornik-pervyy-motor",
	},
	{
		id: 3,
		date: "1 декабря",
		time: "14:00",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "1000 ₸",
		img: images.eventImg2,
		name: "Тюркский разговорник",
		link: "https://sxodim.com/almaty/event/komediynoe-shou-tyurkskiy-razgovornik-pervyy-motor",
	},
	// {
	// 	id: 4,
	// 	date: "1 декабря",
	// 	time: "16:00",
	// 	location: "Almaty Central Stand-Up Club",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	price: "1000 ₸",
	// 	name: "Тюркский разговорник",
	// 	img: images.eventImg3,
	// 	link: "https://sxodim.com/almaty/event/komediynoe-shou-tyurkskiy-razgovornik-pervyy-motor",
	// },
	{
		id: 5,
		date: "1 декабря",
		time: "21:00", //1900
		location: "Coffee House Grain",
		address: "ул. Курмангазы, 97",
		price: "lдонат от 1000 ₸",
		img: images.moneyMike4,
		name: "Money Mic: Отборочный тур",
		link: "https://almaty.qtickets.events/92273-denezhnyy-mikrofon",
	},
	{
		id: 6,
		date: "1 декабря",
		time: "19:00",
		location: "Grain House",
		address: "ул. Курмангазы, 97",
		price: "3000 ₸",
		img: images.double2,
		name: "Концерт: Руслан Тай и Арсен Алтыбаев",
		link: "https://sxodim.com/almaty/event/dvoynoy-stendap-koncert-ruslana-taya-i-arsena-altybaeva",
	},
	{
		id: 7,
		date: "1 декабря",
		time: "19:00",
		location: "in:pace",
		address: "ул. Достык, 132Б",
		price: "5000 ₸",
		name: "Концерт: Вероника и Дамир Нурсеитов",
		link: "",
	},
	{
		id: 8,
		date: "1 декабря",
		time: "19:00",
		location: "Ray Stand-Up Pub",
		address: "ул. Нурмакова, 51а",
		price: "донат от 1000 ₸",
		name: "Мигранты",
		link: "",
	},
	{
		id: 10,
		date: "1 декабря",
		time: "18:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "4000 ₸",
		img: images.kazakhSession,
		name: "Секция Казахского. Съемка",
		link: "https://sxodim.com/almaty/event/poznavatelno-razvlekatelnoe-shou-sekciya-kazahskogo",
	},

	{
		id: 11,
		date: "1 декабря",
		time: "19:30",
		location: "Black Box",
		address: "ул. Кабанбай батыра, 71",
		price: "5000 ₸",
		img: images.charity,
		name: "Благотворительный концерт",
		link: "https://sxodim.com/almaty/event/blagotvoritelnyy-stendap-koncert",
	},
	{
		id: 12,
		date: "1 декабря",
		time: "19:00",
		location: "Цугцванг",
		address: "ул. Толе би, 49",
		price: "донат от 1000 ₸",
		name: "Концерт комиков с Юга",
		link: "https://sxodim.com/almaty/event/komediynoe-shou-tyurkskiy-razgovornik-tretiy-motor",
	},
	{
		id: 13,
		date: "1 декабря",
		time: "21:00",
		location: "Wallride",
		address: "Проспект Абая, 8а",
		price: "донат от 1000 ₸",
		img: images.kazakhmic,
		name: "Қазақша стендап",
		link: "https://sxodim.com/almaty/event/aza-sha-mayk",
	},
	{
		id: 14,
		date: "1 декабря",
		time: "21:00",
		location: "Grain House",
		address: "ул. Курмангазы, 97",
		price: "донат от 1000 ₸",
		name: "Money Mic: Отборочный тур",
		img: images.moneyMike,
		link: "https://almaty.qtickets.events/92257-denezhnyy-mikrofon",
	},
	{
		id: 15,
		date: "1 декабря",
		time: "21:00",
		location: "in:pace",
		address: "ул. Достык, 132Б",
		price: "2000 ₸",
		name: "Женский микрофон",
		link: "",
	},
	{
		id: 16,
		date: "1 декабря",
		time: "21:00",
		location: "Ray Stand-Up Pub",
		address: "ул. Нурмакова, 51а",
		img: images.openmic,
		price: "донат от 1000 ₸",
		name: "Открытый микрофон",
		link: "https://almaty.qtickets.events/92613-otkrytyy-mikrofon",
	},
	{
		id: 17,
		date: "1 декабря",
		time: "20:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "4000 ₸",
		img: images.kazakhSession2,
		name: "Секция Казахского. Съемка",
		link: "https://sxodim.com/almaty/event/poznavatelno-razvlekatelnoe-shou-sekciya-kazahskogo",
	},
	{
		id: 18,
		date: "1 декабря",
		time: "21:30",
		location: "Black Box",
		address: "ул. Кабанбай батыра, 71",
		price: "5000 ₸",
		img: images.orWhat,
		name: "Или чё?",
		link: "https://sxodim.com/almaty/event/improvizacionno-komediynoe-shou-ili-che-1",
	},
	{
		id: 19,
		date: "1 декабря",
		time: "21:00",
		location: "Цугцванг",
		address: "ул. Толе би, 49",
		price: "донат от 1000 ₸",
		name: "English Mic",
		link: "",
	},
	{
		id: 20,
		date: "1 декабря",
		time: "23:00",
		location: "Wallride",
		address: "Проспект Абая, 8а",
		price: "донат от 1000 ₸",
		name: "Открытый микрофон",
		link: "",
	},

	{
		id: 21,
		date: "1 декабря",
		time: "21:00",
		location: "Grain House",
		address: "ул. Курмангазы, 97",
		price: "3000 ₸",
		name: "Концерт алматинских комиков",
		link: "",
	},

	{
		id: 22,
		date: "1 декабря",
		time: "23:00",
		location: "in:pace",
		address: "ул. Достык, 132Б",
		price: "2000 ₸",
		name: "Концерт: Дамир Нурсеитов и Темирлан Жалдыбаев",
		link: "",
	},
	// {
	// 	id: 23,
	// 	date: "1 декабря",
	// 	time: "23:30",
	// 	location: "Almaty Central Stand-Up Club",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	img: images.RoastBattle,
	// 	price: "от 1000 ₸",
	// 	name: "Прожарка",
	// 	link: "",
	// },
	{
		id: 23,
		date: "1 декабря",
		time: "23:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		img: images.roastBattle4,
		price: "от 1000 ₸",
		name: "Прожарка",
		link: "",
	},
	{
		id: 24,
		date: "1 декабря",
		time: "23:00",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "донат от 1000 ₸",
		img: images.taro,
		name: "Таро Шоу",
		link: "https://almaty.qtickets.events/92620-taro-shou",
	},

	{
		id: 25,
		date: "1 декабря",
		time: "22:30",
		location: "Black Box",
		address: "ул. Кабанбай батыра, 71",
		price: "донат от 1000 ₸",
		img: images.roastBattle4,
		name: "Roast Battle Tournament: Round 1",
		link: "https://almaty.qtickets.events/92605-roast-battle",
	},

	// {
	// 	id: 23,
	// 	date: "3 декабря",
	// 	time: "15:00",
	// 	location: "Almaty Central Stand-Up Club",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	img: images.dayMike,
	// 	price: "от 1000 ₸",
	// 	name: "Дневной микрофон",
	// 	link: "",
	// },
	{
		id: 27,
		date: "2 декабря",
		time: "18:00",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "3000 ₸",
		name: "Stand up концерт ”Алматы”",
		link: "",
	},
	{
		id: 28,
		date: "2 декабря",
		time: "18:00",
		location: "Ray Stand-Up Pub",
		address: "ул. Нурмакова, 51а",
		price: "донат от 1000 ₸",
		name: "Вечер импровизации",
		link: "",
	},
	{
		id: 29,
		date: "2 декабря",
		time: "18:00", // время на афише 20:00
		location: "Coffee House Grain",
		address: "ул. Курмангазы, 97",
		price: "от 1000 ₸",
		img: images.kazakhmic2,
		name: "Қазақша стендап",
		link: "https://sxodim.com/almaty/event/aza-sha-mayk-1",
	},
	{
		id: 30,
		date: "2 декабря",
		time: "18:00",
		location: "Цугцванг",
		address: "ул. Толе би, 49",
		price: "донат от 1000 ₸",
		name: "Открытый микрофон",
		link: "",
	},
	{
		id: 31,
		date: "2 декабря",
		time: "18:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "3000 ₸",
		name: "Вечер историй с Нагимой Настевич",
		link: "",
	},
	{
		id: 32,
		date: "2 декабря",
		time: "18:30",
		location: "Wallride",
		address: "Проспект Абая, 8а",
		price: "донат от 1000 ₸",
		img: images.moneyMike5,
		name: "Money Mic: Отборочный тур",
		link: "https://almaty.qtickets.events/92274-denezhnyy-mikrofon",
	},
	{
		id: 33,
		date: "2 декабря",
		time: "20:00",
		location: "Black Box",
		address: "ул. Кабанбай батыра, 71",
		price: "от 5000 ₸",
		img: images.kimura,
		name: "Кимура show. Live",
		link: "https://sxodim.com/almaty/event/komediynoe-shou-kimura-show-live",
	},
	{
		id: 34,
		date: "2 декабря",
		time: "20:00",
		location: "Ray Stand-Up Pub",
		address: "ул. Нурмакова, 51а",
		price: "от 2000 ₸",
		img: images.englishMike,
		name: "English Mic",
		link: "https://almaty.qtickets.events/92288-english-mic",
	},
	{
		id: 35,
		date: "2 декабря",
		time: "20:00",
		location: "Coffee House Grain",
		address: "ул. Курмангазы, 97",
		price: "донат от 1000 ₸",
		img: images.moneyMike2,
		name: "Money Mic: Отборочный тур",
		link: "https://almaty.qtickets.events/92626-denezhnyy-mikrofon",
	},
	{
		id: 36,
		date: "2 декабря",
		time: "20:00",
		location: "Цугцванг",
		address: "ул. Толе би, 49",
		price: "донат от 1000 ₸",
		img: images.west,
		name: "Stand up концерт ”Западный Казахстан”",
		link: "https://almaty.qtickets.events/92890-stand-up-zapadnyy-kazakhstan",
	},
	{
		id: 37,
		date: "2 декабря",
		time: "20:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "от 3000 ₸",
		img: images.adult,
		name: "Взрослый stand up",
		link: "",
	},
	{
		id: 38,
		date: "2 декабря",
		time: "20:30", // время на афише 20:00
		location: "Wallride",
		address: "Проспект Абая, 8а",
		price: "донат от 1000 ₸",
		img: images.openmic2,
		name: "Открытый микрофон",
		link: "https://almaty.qtickets.events/92618-otkrytyy-mikrofon",
	},
	{
		id: 39,
		date: "2 декабря",
		time: "22:00",
		location: "Black Box",
		address: "ул. Кабанбай батыра, 71",
		price: "4000 ₸",
		name: "Прожарка звезды",
		link: "",
	},
	{
		id: 40,
		date: "2 декабря",
		time: "22:00",
		location: "Ray Stand-Up Pub",
		address: "ул. Нурмакова, 51а",
		price: "4000 ₸",
		name: "Кирилл Селегей и Ньургун Атаков: двойной stand up концерт",
		link: "",
	},
	{
		id: 41,
		date: "2 декабря",
		time: "22:00",
		location: "Цугцванг",
		address: "ул. Толе би, 49",
		price: "донат от 1000 ₸",
		name: "Money Mic: Отборочный тур",
		link: "",
	},
	{
		id: 42,
		date: "2 декабря",
		time: "22:00",
		location: "Coffee House Grain",
		address: "ул. Курмангазы, 97",
		price: "донат от 1000 ₸",
		img: images.openmic3,
		name: "Открытый микрофон",
		link: "https://almaty.qtickets.events/92617-otkrytyy-mikrofon",
	},
	{
		id: 43,
		date: "2 декабря",
		time: "22:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "донат от 1000 ₸",
		img: images.roastBattle5,
		name: "Roast Battle Tournament: Round 2",
		link: "https://almaty.qtickets.events/92608-roast-battle-polufinal",
	},
	{
		id: 44,
		date: "2 декабря",
		time: "22:30",
		location: "Wallride",
		address: "Проспект Абая, 8а",
		price: "донат от 1000 ₸",
		img: images.obsticales,
		name: "Стендап с препятствиями",
		link: "https://almaty.qtickets.events/92612-stendap-s-prepyatstviyami",
	},
	{
		id: 45,
		date: "3 декабря",
		time: "18:00",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		img: images.aitpa,
		price: "5000 ₸",
		name: "Aitpa: Live",
		link: "",
	},
	{
		id: 46,
		date: "3 декабря",
		time: "18:00",
		location: "in:pace",
		address: "ул. Достык, 132Б",
		price: "2000 ₸",
		name: "Қазақша стендап",
		link: "",
	},

	{
		id: 47,
		date: "3 декабря",
		time: "18:00",
		location: "Coffee House Grain",
		address: "ул. Курмангазы, 97",
		price: "донат от 1000 ₸",
		img: images.northKazakhstan,
		name: "Stand up концерт ”Северный Казахстан”",
		link: "https://almaty.qtickets.events/92508-stand-up-severnyy-kazakhstan",
	},
	{
		id: 48,
		date: "3 декабря",
		time: "18:00",
		location: "Цугцванг",
		address: "ул. Толе би, 49",
		price: "донат от 1000 ₸",
		name: "Stand up от комикесс",
		link: "",
	},
	{
		id: 49,
		date: "3 декабря",
		time: "18:00",
		location: "Ray Stand-Up Pub",
		address: "ул. Нурмакова, 51а",
		price: "донат от 1000 ₸",
		name: "Открытый микрофон",
		link: "",
	},
	{
		id: 50,
		date: "3 декабря",
		time: "22:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "4000 ₸",
		// img: images.roastBattle6,
		name: "Прожарка звезды",
		link: "",
	},
	{
		id: 51,
		date: "3 декабря",
		time: "18:30",
		location: "Wallride",
		address: "Проспект Абая, 8а",
		price: "донат от 1000 ₸",
		img: images.englishMike2,
		name: "English Mic",
		link: "https://almaty.qtickets.events/92628-english-mic",
	},
	{
		id: 52,
		date: "3 декабря",
		time: "20:00",
		location: "Black Box",
		address: "ул. Кабанбай батыра, 71",
		price: "от 5000 ₸",
		img: images.aitpa2,
		name: "Aitpa: Live",
		link: "",
	},
	{
		id: 53,
		date: "3 декабря",
		time: "20:00",
		location: "Ray Stand-Up Pub",
		address: "ул. Нурмакова, 51а",
		price: "донат от 1000 ₸",
		img: images.barbarianMike,
		name: "Варварский микрофон",
		link: "https://almaty.qtickets.events/92507-varvarskiy-mikrofon",
	},
	{
		id: 54,
		date: "3 декабря",
		time: "20:00",
		location: "in:pace",
		address: "ул. Достык, 132Б",
		price: "5000 ₸",
		name: "Слава Никифоров и Тилеген Еркинбеков: двойной stand up концерт",
		link: "",
	},
	{
		id: 55,
		date: "3 декабря",
		time: "20:00",
		location: "Цугцванг",
		address: "ул. Толе би, 49",
		price: "донат от 1000 ₸",
		name: "Открытый микрофон",
		link: "",
	},
	{
		id: 56,
		date: "3 декабря",
		time: "20:00",
		location: "Coffee House Grain",
		address: "ул. Курмангазы, 97",
		price: "донат от 1000 ₸",
		name: "Stand up концерт ”Караганда”",
		link: "https://almaty.qtickets.events/92625-stand-up-karaganda",
	},
	{
		id: 57,
		date: "3 декабря",
		time: "20:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "3000 ₸",
		img: images.moneyMike3,
		name: "Money mic: финал",
		link: "https://sxodim.com/almaty/event/denezhnyy-mikrofon-final",
	},
	{
		id: 58,
		date: "3 декабря",
		time: "20:30",
		location: "Wallride",
		address: "Проспект Абая, 8а",
		price: "донат от 1000 ₸",
		img: images.zoomers,
		name: "Stand up Зумеры",
		link: "https://almaty.qtickets.events/92289-stendap-zumery",
	},
	{
		id: 59,
		date: "3 декабря",
		time: "22:00",
		location: "Black Box",
		address: "ул. Кабанбай батыра, 71",
		price: "от 1000 ₸",
		img: images.roastBattle6,
		name: "Roast Battle Tournament: Final Round",
		link: "https://sxodim.com/almaty/event/stendap-shou-roast-battle-final",
	},
	{
		id: 60,
		date: "2 декабря",
		time: "22:00",
		location: "in:pace",
		address: "ул. Достык, 132Б",
		name: "Stand up концерт ”Алматы”",
		link: "",
	},
	{
		id: 63,
		date: "2 декабря",
		time: "22:00",
		location: "Black Box",
		address: "ул. Кабанбай батыра, 71",
		price: "от 4000 ₸",
		img: images.roast,
		name: "Прожарка Азамата Маркленова",
		link: "",
	},
	{
		id: 64,
		date: "2 декабря",
		time: "22:00",
		location: "Ray Stand-Up Pub",
		address: "ул. Нурмакова, 51а",
		price: "от 4000 ₸",
		img: images.double,
		name: "Прожарка Азамата Маркленова",
		link: "https://sxodim.com/almaty/event/dvoynoy-stendap-koncert-kirill-selegey-i-nurgun-atakov",
	},
];
const addressesByLocation = [
	{
		address: "ул. Курмангазы, 97",
		lat: 43.243889181641414,
		lng: 76.9315514785571,
	},
	{
		address: "ул. Кабанбай батыра, 71",
		lat: 43.25029688355746,
		lng: 76.95125197413884,
	},
	{
		address: "ул. Достык, 132Б",
		lat: 43.23580122604631,
		lng: 76.95874527801693,
	},
	{
		address: "Проспект Абая, 8а",
		lat: 43.24186447331781,
		lng: 76.95179746112473,
	},
	{
		address: "ул. Толе би, 49",
		lat: 43.255312164990784,
		lng: 76.94722473216866,
	},
	{
		address: "ул. Нурмакова, 51а",
		lat: 43.254165721256896,
		lng: 76.9058160095247,
	},
]; // Create a map for easy lookup based on address
const locationMap = new Map(
	addressesByLocation.map((location) => [location.address, location])
);

let groupIdCounter = 1;

export const eventsByAddress = Object.entries(
	eventsInfo.reduce((acc, event) => {
		const address = event.address;

		if (!acc[address]) {
			acc[address] = {
				id: groupIdCounter++,
				address,
				events: [],
				...locationMap.get(address),
			};
		}

		acc[address].events.push(event);

		return acc;
	}, {})
).map(([key, group]) => group);
console.log(eventsByAddress);

// Now, eventsByAddress contains the desired structure
export const eventsInfoMain = [
	{ id: 1, img: images.formatKimura, name: "Кимура Шоу" },
	{ id: 2, img: images.formatTurk, name: "Тюркский разговорник" },
	{ id: 3, img: images.formatKazakh, name: "Секция Казахского" },
	{ id: 4, img: images.formatAitpa, name: "Aitpa: Live" },
];

eventsInfo.sort((a, b) => {
	// Extract day as a number
	const dayA = parseInt(a.date.split(" ")[0]);
	const dayB = parseInt(b.date.split(" ")[0]);

	// Compare days
	if (dayA < dayB) {
		return -1;
	} else if (dayA > dayB) {
		return 1;
	} else {
		// If days are equal, compare times
		const timeA = new Date(`1970/01/01 ${a.time}`);
		const timeB = new Date(`1970/01/01 ${b.time}`);
		return timeA - timeB;
	}
});

export let eventsDatesArray = [];
const eventsDates = new Set();
eventsInfo.map((event) => eventsDates.add(event.date));
eventsDatesArray = [...eventsDates];
