import images from "../assets/images/images";

export const eventsInfo = [
	// {
	// 	id: 2,
	// 	date: "1 декабря",
	// 	time: "12:00",
	// 	location: "Almaty Central Stand-Up Club",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	price: "1000 ₸",
	// 	img: images.eventImg1,
	// 	name: "Тюркский разговорник",
	// 	link: "https://sxodim.com/almaty/event/komediynoe-shou-tyurkskiy-razgovornik-pervyy-motor",
	// },
	// {
	// 	id: 1,
	// 	date: "1 декабря",
	// 	time: "16:00",
	// 	location: "Almaty Central Stand-Up Club",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	price: "1000 ₸",
	// 	img: images.eventImg3,
	// 	name: "Тюркский разговорник",
	// 	link: "https://sxodim.com/almaty/event/komediynoe-shou-tyurkskiy-razgovornik-pervyy-motor",
	// },
	// {
	// 	id: 3,
	// 	date: "1 декабря",
	// 	time: "14:00",
	// 	location: "Almaty Central Stand-Up Club",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	price: "1000 ₸",
	// 	img: images.eventImg2,
	// 	name: "Тюркский разговорник",
	// 	link: "https://sxodim.com/almaty/event/komediynoe-shou-tyurkskiy-razgovornik-pervyy-motor",
	// },
	// // {
	// // 	id: 4,
	// // 	date: "1 декабря",
	// // 	time: "16:00",
	// // 	location: "Almaty Central Stand-Up Club",
	// // 	address: "ул. Кабанбай батыра, 71",
	// // 	price: "1000 ₸",
	// // 	name: "Тюркский разговорник",
	// // 	img: images.eventImg3,
	// // 	link: "https://sxodim.com/almaty/event/komediynoe-shou-tyurkskiy-razgovornik-pervyy-motor",
	// // },
	// {
	// 	id: 5,
	// 	date: "1 декабря",
	// 	time: "19:00", //1900
	// 	location: "Wallride",
	// 	address: "Проспект Абая, 8а",
	// 	price: "донат от 1000 ₸",
	// 	img: images.moneyMike4,
	// 	name: "Wallride Money Mic. Отборочный тур",
	// 	link: "https://almaty.qtickets.events/92273-denezhnyy-mikrofon",
	// },
	// {
	// 	id: 6,
	// 	date: "1 декабря",
	// 	time: "19:00",
	// 	location: "Grain House",
	// 	address: "ул. Курмангазы, 97",
	// 	price: "3000 ₸",
	// 	img: images.double2,
	// 	name: "Концерт: Руслан Тай и Арсен Алтыбаев",
	// 	link: "https://sxodim.com/almaty/event/dvoynoy-stendap-koncert-ruslana-taya-i-arsena-altybaeva",
	// },
	// {
	// 	id: 7,
	// 	date: "1 декабря",
	// 	time: "19:00",
	// 	location: "in:pace",
	// 	address: "ул. Достык, 132Б",
	// 	price: "5000 ₸",
	// 	img: images.double4,
	// 	name: "Концерт: Вероника и Мадияр Нурманбетов",
	// 	link: "https://sxodim.com/almaty/event/veronika-kim-i-madiyar-nurmanbetov-dvoynoy-stendap-koncert",
	// },
	// {
	// 	id: 8,
	// 	date: "1 декабря",
	// 	time: "19:00",
	// 	location: "Ray Stand-Up Pub",
	// 	address: "ул. Нурмакова, 51а",
	// 	price: "донат от 1000 ₸",
	// 	img: images.migrants,
	// 	name: "Мигранты",
	// 	link: "https://almaty.qtickets.events/93103-stand-up-migranty",
	// },
	// {
	// 	id: 10,
	// 	date: "1 декабря",
	// 	time: "19:00",
	// 	location: "Almaty Central Stand-Up Club",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	price: "4000 ₸",
	// 	img: images.kazakhSession,
	// 	name: "Секция Казахского. Съемка",
	// 	link: "https://sxodim.com/almaty/event/poznavatelno-razvlekatelnoe-shou-sekciya-kazahskogo",
	// },

	// {
	// 	id: 11,
	// 	date: "1 декабря",
	// 	time: "19:30",
	// 	location: "Black Box",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	price: "5000 ₸",
	// 	img: images.charity,
	// 	name: "Благотворительный концерт",
	// 	link: "https://sxodim.com/almaty/event/blagotvoritelnyy-stendap-koncert",
	// },
	// {
	// 	id: 12,
	// 	date: "1 декабря",
	// 	time: "19:00",
	// 	location: "Цугцванг",
	// 	address: "ул. Толе би, 49",
	// 	price: "донат от 1000 ₸",
	// 	name: "Концерт комиков с Юга",
	// 	img: images.south,
	// 	link: "https://almaty.qtickets.events/93192-stand-up-komiki-s-yuga",
	// },
	// {
	// 	id: 13,
	// 	date: "1 декабря",
	// 	time: "21:00",
	// 	location: "Wallride",
	// 	address: "Проспект Абая, 8а",
	// 	price: "донат от 1000 ₸",
	// 	img: images.kazakhmic,
	// 	name: "Қазақша стендап",
	// 	link: "https://sxodim.com/almaty/event/aza-sha-mayk",
	// },
	// {
	// 	id: 14,
	// 	date: "1 декабря",
	// 	time: "21:00",
	// 	location: "Wallride",
	// 	address: "Проспект Абая, 8а",
	// 	price: "донат от 1000 ₸",
	// 	name: "Wallride Money Mic. Отборочный тур",
	// 	img: images.moneyMike,
	// 	link: "https://almaty.qtickets.events/92257-denezhnyy-mikrofon",
	// },
	// {
	// 	id: 15,
	// 	date: "1 декабря",
	// 	time: "21:00",
	// 	location: "in:pace",
	// 	address: "ул. Достык, 132Б",
	// 	price: "2000 ₸",
	// 	img: images.female2,
	// 	name: "Stand up от комикесс ",
	// 	link: "https://sxodim.com/almaty/event/stand-up-koncert-ot-komikess",
	// },
	// {
	// 	id: 16,
	// 	date: "1 декабря",
	// 	time: "21:00",
	// 	location: "Ray Stand-Up Pub",
	// 	address: "ул. Нурмакова, 51а",
	// 	img: images.openmic,
	// 	price: "донат от 1000 ₸",
	// 	name: "Открытый микрофон",
	// 	link: "https://almaty.qtickets.events/92613-otkrytyy-mikrofon",
	// },
	// {
	// 	id: 17,
	// 	date: "1 декабря",
	// 	time: "21:00",
	// 	location: "Almaty Central Stand-Up Club",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	price: "4000 ₸",
	// 	img: images.kazakhSession2,
	// 	name: "Секция Казахского. Съемка",
	// 	link: "https://sxodim.com/almaty/event/poznavatelno-razvlekatelnoe-shou-sekciya-kazahskogo",
	// },
	// {
	// 	id: 18,
	// 	date: "1 декабря",
	// 	time: "21:30",
	// 	location: "Black Box",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	price: "5000 ₸",
	// 	img: images.orWhat,
	// 	name: "Или чё?",
	// 	link: "https://sxodim.com/almaty/event/improvizacionno-komediynoe-shou-ili-che-1",
	// },

	// {
	// 	id: 23,
	// 	date: "1 декабря",
	// 	time: "23:30",
	// 	location: "Almaty Central Stand-Up Club",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	img: images.RoastBattle,
	// 	price: "от 1000 ₸",
	// 	name: "Прожарка",
	// 	link: "",
	// },
	// {
	// 	id: 23,
	// 	date: "1 декабря",
	// 	time: "23:30",
	// 	location: "Almaty Central Stand-Up Club",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	img: images.roastBattle4,
	// 	price: "от 1000 ₸",
	// 	name: "Прожарка",
	// 	link: "",
	// // },
	// {
	// 	id: 24,
	// 	date: "1 декабря",
	// 	time: "23:00",
	// 	location: "Almaty Central Stand-Up Club",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	price: "донат от 1000 ₸",
	// 	img: images.taro,
	// 	name: "Таро Шоу",
	// 	link: "https://almaty.qtickets.events/92620-taro-shou",
	// },

	// {
	// 	id: 25,
	// 	date: "1 декабря",
	// 	time: "23:30",
	// 	location: "Black Box",
	// 	address: "ул. Кабанбай батыра, 71",
	// 	price: "донат от 1000 ₸",
	// 	img: images.roastBattle4,
	// 	name: "Roast Battle Tournament: Round 1",
	// 	link: "https://almaty.qtickets.events/92605-roast-battle",
	// },

	{
		id: 23,
		date: "3 декабря",
		time: "15:00",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		img: images.dayMike,
		price: "от 1000 ₸",
		name: "Дневной микрофон",
		link: "https://almaty.qtickets.events/92675-dnevnoy-mikrofon",
	},
	{
		id: 27,
		date: "2 декабря",
		time: "18:00",
		location: "Almaty Central Stand up club",
		address: "ул. Кабанбай батыра, 71",
		price: "5000 ₸",
		img: images.big,
		name: "Большой алматинский стендап-концерт",
		link: "https://sxodim.com/almaty/event/bolshoy-almatinskiy-stendap-koncert",
	},
	/////////////////////////////////////////////////////////////////////////////////

	// {
	// 	id: 20,
	// 	date: "1 декабря",
	// 	time: "23:00",
	// 	location: "Wallride",
	// 	address: "Проспект Абая, 8а",
	// 	price: "донат от 1000 ₸",
	// 	img: images.openmic7,
	// 	name: "Открытый микрофон",
	// 	link: "https://almaty.qtickets.events/93193-otkrytyy-mikrofon",
	// },

	// {
	// 	id: 19,
	// 	date: "1 декабря",
	// 	time: "21:00",
	// 	location: "Цугцванг",
	// 	address: "ул. Толе би, 49",
	// 	price: "донат от 1000 ₸",
	// 	img: images.englishMike3,
	// 	name: "English Mic",
	// 	link: "https://almaty.qtickets.events/93106-english-mic",
	// },
	// {
	// 	id: 66,
	// 	date: "1 декабря",
	// 	time: "23:00",
	// 	location: "Coffee House Grain",
	// 	address: "ул. Курмангазы, 97",
	// 	price: "5000 ₸",
	// 	img: images.locals,
	// 	name: "Концерт алматинских комиков",
	// 	link: "https://sxodim.com/almaty/event/stand-up-almaty-koncert-mestnyh-komikov",
	// },
	{
		id: 28,
		date: "2 декабря",
		time: "18:00",
		location: "Ray Stand-Up Pub",
		address: "ул. Нурмакова, 51а",
		price: "донат от 1000 ₸",
		img: images.imporovJam,
		name: "Вечер импровизации",
		link: "https://almaty.qtickets.events/93107-improv-jam",
	},

	{
		id: 41,
		date: "2 декабря",
		time: "22:00",
		location: "Цугцванг",
		address: "ул. Толе би, 49",
		price: "донат от 1000 ₸",
		img: images.moneyMike6,
		name: "Money Mic: Отборочный тур",
		link: "https://almaty.qtickets.events/93099-denezhnyy-mikrofon",
	},
	{
		id: 30,
		date: "2 декабря",
		time: "18:00",
		location: "Цугцванг",
		address: "ул. Толе би, 49",
		price: "донат от 1000 ₸",
		img: images.openmic4,
		name: "Открытый микрофон",
		link: "https://almaty.qtickets.events/92618-otkrytyy-mikrofon",
	},
	{
		id: 60,
		date: "3 декабря",
		time: "22:00",
		location: "in:pace",
		address: "ул. Достык, 132Б",
		price: "3000 ₸",
		img: images.locals2,
		name: "Концерт алматинских комиков",
		link: "https://sxodim.com/almaty/event/almatinskiy-koncert-koncert-mestnyh-komikov",
	},
	{
		id: 48,
		date: "3 декабря",
		time: "18:00",
		location: "Цугцванг",
		address: "ул. Толе би, 49",
		price: "донат от 1000 ₸",
		img: images.female,
		name: "Stand up от комикесс",
		link: "https://almaty.qtickets.events/93098-stand-up-ot-komikess",
	},
	{
		id: 46,
		date: "3 декабря",
		time: "18:00",
		location: "in:pace",
		address: "ул. Достык, 132Б",
		price: "2000 ₸",
		img: images.kazakhmic3,
		name: "Қазақша стендап",
		link: "https://sxodim.com/almaty/event/aza-sha-stendap-koncert-1",
	},
	{
		id: 49,
		date: "3 декабря",
		time: "18:00",
		location: "Ray Stand-Up Pub",
		address: "ул. Нурмакова, 51а",
		price: "донат от 1000 ₸",
		img: images.openmic5,
		name: "Открытый микрофон",
		link: "https://almaty.qtickets.events/93101-otkrytyy-mikrofon",
	},
	{
		id: 54,
		date: "3 декабря",
		time: "20:00",
		location: "in:pace",
		address: "ул. Достык, 132Б",
		price: "5000 ₸",
		img: images.double5,
		name: "Слава Никифоров и Тилеген Еркинбеков: двойной stand up концерт",
		link: "https://sxodim.com/almaty/event/slava-nikiforov-i-tilegen-erkinbekov-dvoynoy-stendap-koncert",
	},
	{
		id: 55,
		date: "3 декабря",
		time: "20:00",
		location: "Цугцванг",
		address: "ул. Толе би, 49",
		price: "донат от 1000 ₸",
		img: images.openmic6,
		name: "Открытый микрофон",
		link: "https://almaty.qtickets.events/93108-otkrytyy-mikrofon",
	},
	//************************************************************ */
	{
		id: 29,
		date: "2 декабря",
		time: "18:00", // время на афише 20:00
		location: "Coffee House Grain",
		address: "ул. Курмангазы, 97",
		price: "от 1000 ₸",
		img: images.kazakhmic2,
		name: "Қазақша стендап",
		link: "https://sxodim.com/almaty/event/aza-sha-mayk-1",
	},

	{
		id: 31,
		date: "2 декабря",
		time: "18:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "3000 ₸",
		img: images.history,
		name: "Вечер историй с Нагимой Настевич",
		link: "https://sxodim.com/almaty/event/razvlekatelnoe-shou-vecher-istoriy-s-nagimoy-nastevich",
	},
	{
		id: 32,
		date: "2 декабря",
		time: "18:30",
		location: "Wallride",
		address: "Проспект Абая, 8а",
		price: "донат от 1000 ₸",
		img: images.moneyMike5,
		name: "Wallride Money Mic. Отборочный тур",
		link: "https://almaty.qtickets.events/92274-denezhnyy-mikrofon",
	},
	{
		id: 33,
		date: "2 декабря",
		time: "20:00",
		location: "Black Box",
		address: "ул. Кабанбай батыра, 71",
		price: "от 5000 ₸",
		img: images.kimura,
		name: "Кимура show. Live",
		link: "https://sxodim.com/almaty/event/komediynoe-shou-kimura-show-live",
	},
	{
		id: 34,
		date: "2 декабря",
		time: "20:00",
		location: "Ray Stand-Up Pub",
		address: "ул. Нурмакова, 51а",
		price: "от 2000 ₸",
		img: images.englishMike,
		name: "English Mic",
		link: "https://almaty.qtickets.events/92288-english-mic",
	},
	{
		id: 35,
		date: "2 декабря",
		time: "20:00",
		location: "Coffee House Grain",
		address: "ул. Курмангазы, 97",
		price: "донат от 1000 ₸",
		img: images.moneyMike2,
		name: "Money Mic. Отборочный тур",
		link: "https://almaty.qtickets.events/92626-denezhnyy-mikrofon",
	},
	{
		id: 36,
		date: "2 декабря",
		time: "20:00",
		location: "Цугцванг",
		address: "ул. Толе би, 49",
		price: "донат от 1000 ₸",
		img: images.west,
		name: "Stand up концерт ”Западный Казахстан”",
		link: "https://almaty.qtickets.events/92890-stand-up-zapadnyy-kazakhstan",
	},
	{
		id: 37,
		date: "2 декабря",
		time: "20:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "от 3000 ₸",
		img: images.adult,
		name: "Взрослый stand up",
		link: "https://sxodim.com/almaty/event/stendap-koncert-vzroslyy-stand-up",
	},

	{
		id: 38,
		date: "2 декабря",
		time: "20:00", // время на афише 20:00
		location: "Wallride",
		address: "Проспект Абая, 8а",
		price: "донат от 1000 ₸",
		img: images.openmic2,
		name: "Открытый микрофон",
		link: "https://almaty.qtickets.events/92618-otkrytyy-mikrofon",
	},

	// {
	// 	id: 40,
	// 	date: "2 декабря",
	// 	time: "22:00",
	// 	location: "Ray Stand-Up Pub",
	// 	address: "ул. Нурмакова, 51а",
	// 	price: "4000 ₸",
	// 	name: "Кирилл Селегей и Ньургун Атаков: двойной stand up концерт",
	// 	link: "",
	// },

	{
		id: 42,
		date: "2 декабря",
		time: "22:00",
		location: "Coffee House Grain",
		address: "ул. Курмангазы, 97",
		price: "донат от 1000 ₸",
		img: images.openmic3,
		name: "Открытый микрофон",
		link: "https://almaty.qtickets.events/92617-otkrytyy-mikrofon",
	},
	{
		id: 43,
		date: "2 декабря",
		time: "22:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "донат от 1000 ₸",
		img: images.roastBattle5,
		name: "Roast Battle Tournament: Round 2",
		link: "https://almaty.qtickets.events/92608-roast-battle-polufinal",
	},
	{
		id: 44,
		date: "2 декабря",
		time: "22:00",
		location: "Wallride",
		address: "Проспект Абая, 8а",
		price: "донат от 1000 ₸",
		img: images.obsticales,
		name: "Стендап с препятствиями",
		link: "https://almaty.qtickets.events/92612-stendap-s-prepyatstviyami",
	},
	{
		id: 45,
		date: "3 декабря",
		time: "18:00",
		location: "Black Box",
		address: "ул. Кабанбай батыра, 71",
		img: images.aitpa,
		price: "5000 ₸",
		name: "Aitpa: Live",
		link: "https://sxodim.com/almaty/event/stendap-shou-aitpa-live",
	},

	{
		id: 47,
		date: "3 декабря",
		time: "18:00",
		location: "Coffee House Grain",
		address: "ул. Курмангазы, 97",
		price: "донат от 1000 ₸",
		img: images.northKazakhstan,
		name: "Stand up концерт ”Северный Казахстан”",
		link: "https://almaty.qtickets.events/92508-stand-up-severnyy-kazakhstan",
	},

	{
		id: 50,
		date: "3 декабря",
		time: "18:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "3000 ₸",
		img: images.roast2,
		name: "Прожарка Moreart",
		link: "https://sxodim.com/almaty/event/prozharka-moreart",
	},
	{
		id: 51,
		date: "3 декабря",
		time: "18:30",
		location: "Wallride",
		address: "Проспект Абая, 8а",
		price: "донат от 1000 ₸",
		img: images.englishMike2,
		name: "English Mic",
		link: "https://almaty.qtickets.events/92628-english-mic",
	},
	{
		id: 52,
		date: "3 декабря",
		time: "20:00",
		location: "Black Box",
		address: "ул. Кабанбай батыра, 71",
		price: "от 5000 ₸",
		img: images.aitpa2,
		name: "Aitpa: Live",
		link: "https://sxodim.com/almaty/event/stendap-shou-aitpa-live",
	},
	{
		id: 53,
		date: "3 декабря",
		time: "20:00",
		location: "Ray Stand-Up Pub",
		address: "ул. Нурмакова, 51а",
		price: "донат от 1000 ₸",
		img: images.barbarianMike,
		name: "Варварский микрофон",
		link: "https://almaty.qtickets.events/92507-varvarskiy-mikrofon",
	},

	{
		id: 56,
		date: "3 декабря",
		time: "20:00",
		location: "Coffee House Grain",
		address: "ул. Курмангазы, 97",
		price: "донат от 1000 ₸",
		img: images.karaganda,
		name: "Stand up концерт ”Караганда”",
		link: "https://almaty.qtickets.events/92625-stand-up-karaganda",
	},
	{
		id: 57,
		date: "3 декабря",
		time: "20:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "3000 ₸",
		img: images.moneyMike3,
		name: "Money mic: финал",
		link: "https://sxodim.com/almaty/event/denezhnyy-mikrofon-final",
	},
	{
		id: 58,
		date: "3 декабря",
		time: "20:30",
		location: "Wallride",
		address: "Проспект Абая, 8а",
		price: "донат от 1000 ₸",
		img: images.zoomers,
		name: "Stand up Зумеры",
		link: "https://almaty.qtickets.events/92289-stendap-zumery",
	},
	{
		id: 59,
		date: "3 декабря",
		time: "22:00",
		location: "Black Box",
		address: "ул. Кабанбай батыра, 71",
		price: "от 1000 ₸",
		img: images.roastBattle6,
		name: "Roast Battle Tournament: Final Round",
		link: "https://sxodim.com/almaty/event/stendap-shou-roast-battle-final",
	},

	{
		id: 63,
		date: "2 декабря",
		time: "22:00",
		location: "Black Box",
		address: "ул. Кабанбай батыра, 71",
		price: "от 4000 ₸",
		img: images.roast,
		name: "Прожарка Азамата Маркленова",
		link: "https://sxodim.com/almaty/event/prozharka-azamata-marklenova",
	},
	{
		id: 64,
		date: "2 декабря",
		time: "22:00",
		location: "Ray Stand-Up Pub",
		address: "ул. Нурмакова, 51а",
		price: "от 4000 ₸",
		img: images.double,
		name: "Двойной стендап-концерт: Кирилл Селегей и Ньургун Атаков",
		link: "https://sxodim.com/almaty/event/dvoynoy-stendap-koncert-kirill-selegey-i-nurgun-atakov",
	},
	{
		id: 65,
		date: "3 декабря",
		time: "22:30",
		location: "Almaty Central Stand-Up Club",
		address: "ул. Кабанбай батыра, 71",
		price: "от 5000 ₸",
		img: images.double3,
		name: "Биржан Кабылбаев и Шынгыс Ермек: двойной stand up концерт",
		link: "https://sxodim.com/almaty/event/birzhan-kabylbaev-i-shyngys-ermek-dvoynoy-stendap-koncert",
	},
	// {
	// 	id: 66,
	// 	date: "1 декабря",
	// 	time: "23:00",
	// 	location: "in:pace",
	// 	address: "ул. Достык, 132Б",
	// 	price: "3000 ₸",
	// 	img: images.double6,
	// 	name: "Темирлан Жалдыбаев и Витя Копаница: двойной stand up концерт",
	// 	link: "https://sxodim.com/almaty/event/temirlan-zhaldybaev-i-viktor-kopanica-dvoynoy-stendap-koncert",
	// },
];
export const eventsLength = eventsInfo.length;
const addressesByLocation = [
	{
		address: "ул. Курмангазы, 97",
		lat: 43.243889181641414,
		lng: 76.9315514785571,
	},
	{
		address: "ул. Кабанбай батыра, 71",
		lat: 43.25029688355746,
		lng: 76.95125197413884,
	},
	{
		address: "ул. Достык, 132Б",
		lat: 43.23580122604631,
		lng: 76.95874527801693,
	},
	{
		address: "Проспект Абая, 8а",
		lat: 43.24186447331781,
		lng: 76.95179746112473,
	},
	{
		address: "ул. Толе би, 49",
		lat: 43.255312164990784,
		lng: 76.94722473216866,
	},
	{
		address: "ул. Нурмакова, 51а",
		lat: 43.254165721256896,
		lng: 76.9058160095247,
	},
]; // Create a map for easy lookup based on address
const locationMap = new Map(
	addressesByLocation.map((location) => [location.address, location])
);

let groupIdCounter = 1;

export const eventsByAddress = Object.entries(
	eventsInfo.reduce((acc, event) => {
		const address = event.address;

		if (!acc[address]) {
			acc[address] = {
				id: groupIdCounter++,
				address,
				events: [],
				...locationMap.get(address),
			};
		}

		acc[address].events.push(event);

		return acc;
	}, {})
).map(([key, group]) => group);
// Now, eventsByAddress contains the desired structure
export const eventsInfoMain = [
	{ id: 1, img: images.formatKimura, name: "Кимура Шоу" },
	{ id: 2, img: images.formatTurk, name: "Тюркский разговорник" },
	{ id: 3, img: images.formatKazakh, name: "Секция Казахского" },
	{ id: 4, img: images.formatAitpa, name: "Aitpa: Live" },
];

eventsInfo.sort((a, b) => {
	// Extract day as a number
	const dayA = parseInt(a.date.split(" ")[0]);
	const dayB = parseInt(b.date.split(" ")[0]);

	// Compare days
	if (dayA < dayB) {
		return -1;
	} else if (dayA > dayB) {
		return 1;
	} else {
		// If days are equal, compare times
		const timeA = new Date(`1970/01/01 ${a.time}`);
		const timeB = new Date(`1970/01/01 ${b.time}`);
		return timeA - timeB;
	}
});

export let eventsDatesArray = [];
const eventsDates = new Set();
eventsInfo.map((event) => eventsDates.add(event.date));
eventsDatesArray = [...eventsDates];
